/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import javax.swing.JOptionPane;

/**
 *
 * @author angelica
 */
public class FormTiket extends javax.swing.JFrame {

    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Airlines = new javax.swing.JLabel();
        FromField = new javax.swing.JTextField();
        From = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        ToField = new javax.swing.JTextField();
        Tanggal = new javax.swing.JComboBox<>();
        Tahun = new javax.swing.JTextField();
        NamaPesawatField = new javax.swing.JComboBox<>();
        Ticket = new javax.swing.JLabel();
        IsiTiket = new javax.swing.JTextField();
        Total = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        IDR = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        Bulan = new javax.swing.JComboBox<>();
        btnDone = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1264, 841));
        setMinimumSize(new java.awt.Dimension(1264, 841));
        setPreferredSize(new java.awt.Dimension(1264, 841));
        setSize(new java.awt.Dimension(1264, 841));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 22, -1, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Halo,,");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 111, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.activeCaption);
        jLabel3.setText("PLAN YOUR JOURNEY ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 420, 50));

        Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 37, -1));

        Airlines.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Airlines.setForeground(new java.awt.Color(255, 255, 255));
        Airlines.setText("Arlines");
        getContentPane().add(Airlines, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 58, -1));

        FromField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FromField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 151, 33));

        From.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        From.setForeground(new java.awt.Color(255, 255, 255));
        From.setText("From");
        getContentPane().add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 58, -1));

        To.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        To.setForeground(new java.awt.Color(255, 255, 255));
        To.setText("To");
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 58, -1));

        ToField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ToField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 151, 33));

        Tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 151, 37));

        Tahun.setText("2024");
        Tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunActionPerformed(evt);
            }
        });
        getContentPane().add(Tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 120, 37));

        NamaPesawatField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(NamaPesawatField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 151, 36));

        Ticket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ticket.setForeground(new java.awt.Color(255, 255, 255));
        Ticket.setText("Ticket");
        getContentPane().add(Ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 58, -1));

        IsiTiket.setText("1");
        IsiTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiTiketActionPerformed(evt);
            }
        });
        getContentPane().add(IsiTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 140, 30));

        Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("Total");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 67, 25));

        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 114, 30));

        IDR.setForeground(new java.awt.Color(255, 255, 255));
        IDR.setText("IDR");
        getContentPane().add(IDR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 31, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 730, 101, 33));

        Bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "July", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(Bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 174, 37));

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        getContentPane().add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 730, 95, 33));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\angelica\\Documents\\NetBeansProjects\\Project_tiket_pesawat\\src\\main\\java\\Assets\\low-angle-shot-airplane-flying-closer-daytime (3).jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FromFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromFieldActionPerformed

    private void ToFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToFieldActionPerformed

    private void TahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunActionPerformed

    private void IsiTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiTiketActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FormLogin role = new FormLogin();
        role.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin menyelesaikan pemesanan?", 
        "Konfirmasi Pemesanan", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);

    if (response == JOptionPane.YES_OPTION) {
        // User clicked Yes, proceed to perform the desired action (like opening the Alert dialog)
        JOptionPane confirm = new JOptionPane(); // Ensure Alert is a JFrame or JDialog
        confirm.setVisible(true); // Show the Alert dialog
        
        // Close the current form
    } else {
        // User clicked No, do nothing or show a message
        JOptionPane.showMessageDialog(this, "Pemesanan dibatalkan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    }              
    }//GEN-LAST:event_btnDoneActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Airlines;
    private javax.swing.JComboBox<String> Bulan;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel From;
    private javax.swing.JTextField FromField;
    private javax.swing.JLabel IDR;
    private javax.swing.JTextField IsiTiket;
    private javax.swing.JComboBox<String> NamaPesawatField;
    private javax.swing.JTextField Tahun;
    private javax.swing.JComboBox<String> Tanggal;
    private javax.swing.JLabel Ticket;
    private javax.swing.JLabel To;
    private javax.swing.JTextField ToField;
    private javax.swing.JLabel Total;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
